services:
    postgres:
        image: postgres:16
        platform: linux/amd64
        ports:
            - "5432:5432"
        env_file: ".env"
        networks:
            - schedule_net
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    schedule_app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            FLASK_DEBUG: "true"
        ports:
            - "3000:3000"
        networks:
            - schedule_net
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    pg_data:

networks:
    schedule_net: {}
